### ISSUE TITLE
Is the file that you are creating with CTRL+ALT+N actually in your file system or is it a scratch file?

### ISSUE THREAD

**Issue by Hessiinlove** [Hessiinlove/urban-disco#1]
Is the file that you are creating with CTRL+ALT+N actually in your file system or is it a scratch file?

What minifyall command are you using?

May you send a video so I can see what the exact problem is?

Thanks!

_Originally posted by @Josee9988 in https://github.com/Josee9988/MinifyAll/issues/93#issuecomment-816020927_

**Comment by Hessiinlove** [comment]
> Is the file that you are creating with CTRL+ALT+N actually in your file system or is it a scratch file?
> 
> What minifyall command are you using?
> 
> May you send a video so I can see what the exact problem is?
> 
> Thanks!
> 
> _Originally posted by @Josee9988 in [Josee9988/MinifyAll#93 (comment)](https://github.com/Josee9988/MinifyAll/issues/93#issuecomment-816020927)_

**Comment by Josee9988** [comment]
Hey😅 what is this?

**Comment by Hessiinlove** [comment]
> Is the file that you are creating with CTRL+ALT+N actually in your file system or is it a scratch file?
> 
> What minifyall command are you using?
> 
> May you send a video so I can see what the exact problem is?
> 
> Thanks!
> 
> _Originally posted by @Josee9988 in [Josee9988/MinifyAll#93 (comment)](https://github.com/Josee9988/MinifyAll/issues/93#issuecomment-816020927)_

**Comment by Josee9988** [comment]
Is this an issue related to MinifyAll? if so what is this repo "urban-disco"?, this doesn't seem like a vscode extension that might have the same issue :D
